server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/auto_attendance_pbl5?createDatabaseIfNotExist=true"
#    url: "jdbc:mysql://localhost:3306/auto_attendance_pbl5?createDatabaseIfNotExist=true"
#    url: "jdbc:mysql://localhost:3306/auto_attendance_pbl5?createDatabaseIfNotExist=true"
    username: root
#    password: Trantai25022004
#    password: 110204
    password: phong123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
#    database: mysql
  app:
    jwtSecret: mySecretkey1231738qwfqwfqowuhfnoqwuhfqwoifnjqwipfjpi
    accessTokenExpirationMs: 3600000
    refreshTokenExpirationMs: 604800000

